const NOT_FOUND_CODE_STATUS = 404;
const VALIDATION_CODE_STATUS = 400;
const DEFAULT_CODE_STATUS = 500;
const OK_CODE_STATUS = 200;
const CREATED_CODE_STATUS = 201;

module.exports = {
  NOT_FOUND_CODE_STATUS,
  VALIDATION_CODE_STATUS,
  DEFAULT_CODE_STATUS,
  OK_CODE_STATUS,
  CREATED_CODE_STATUS,
};
